// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QTip.Infrastructure.Persistence;

#nullable disable

namespace QTip.Infrastructure.Data.Migrations
{
    [DbContext(typeof(QTipDbContext))]
    [Migration("20251214232010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QTip.Domain.Entities.ClassifiedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("Tag", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("classified_items", (string)null);
                });

            modelBuilder.Entity("QTip.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenizedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("QTip.Domain.Entities.SubmissionClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassifiedItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("StartIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassifiedItemId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("submission_classifications", (string)null);
                });

            modelBuilder.Entity("QTip.Domain.Entities.SubmissionClassification", b =>
                {
                    b.HasOne("QTip.Domain.Entities.ClassifiedItem", "ClassifiedItem")
                        .WithMany("Occurrences")
                        .HasForeignKey("ClassifiedItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QTip.Domain.Entities.Submission", "Submission")
                        .WithMany("Classifications")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassifiedItem");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("QTip.Domain.Entities.ClassifiedItem", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("QTip.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Classifications");
                });
#pragma warning restore 612, 618
        }
    }
}
